# Generated by Django 6.1.1 on 2026-09-17 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='キー')),
                ('name', models.CharField(max_length=100, verbose_name='表示名')),
                ('role_prompt', models.TextField(verbose_name='ロールプロンプト')),
                ('callable_from_chat', models.BooleanField(default=False, help_text='有効にすると、ヒアリングエージェントが依頼者の入力からこのエージェントの呼び出しを提案できる', verbose_name='対話から呼び出せる')),
                ('call_description', models.TextField(blank=True, help_text='どんな入力のときに呼び出すべきかを、ヒアリングエージェント向けに書く', verbose_name='呼び出しの判断のための説明')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'エージェント',
                'verbose_name_plural': 'エージェント',
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='表示名')),
                ('prompt', models.TextField(verbose_name='プロンプト')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': 'テンプレ',
                'verbose_name_plural': 'テンプレ',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付（日本時間）')),
                ('agent_key', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cache_creation_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='agents_usag_user_id_4b873b_idx')],
            },
        ),
    ]
