# Generated by Django 6.1.1 on 2026-09-17 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body_markdown', models.TextField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('handling_status', models.CharField(choices=[('new', '未対応'), ('in_progress', '対応中'), ('done', '対応済み')], default='new', max_length=20)),
                ('mail_status', models.CharField(choices=[('pending', '未送信'), ('sent', '送信済み'), ('failed', '送信失敗')], default='pending', max_length=20)),
                ('mail_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['submitted_at'], name='summaries_r_submitt_6ea138_idx'), models.Index(fields=['handling_status'], name='summaries_r_handlin_90487e_idx')],
            },
        ),
    ]
